### PR TITLE
added temp conversion support 

### PR DESCRIPTION
**Pull request by theonlytruebigmac**
updated readme with some more information around the docker setup and added F to C conversion in main.go

### CODE REVIEW

**Comment by cdzombak** [comment]
@ablyler as I don't currently have an Ecobee, would you be able to test this branch out at some point?

**Comment by ablyler** [comment]
> @ablyler as I don't currently have an Ecobee, would you be able to test this branch out at some point?

sure!

**Comment by ablyler** [comment]
@cdzombak tested and verified it works! 👍

**Comment by cdzombak** [comment]
@theonlytruebigmac Thank you for this PR!

There is at least one subtle bug: [the indoor humidity recommendation is calculated based on a Fahrenheit temperature](https://github.com/cdzombak/ecobee_influx_connector/pull/37/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R394), while with this PR we my end up passing in a Celsius temperature.

This sort of mixup is what I'm trying to avoid by more extensively using [types declared by libwx](https://github.com/cdzombak/libwx/blob/main/temperature_types.go).

Could you take a look at #39, please? I've implemented Celsius support there slightly differently (by just writing both temperature units to Influx; clients can choose which one they want to display), and also incorporated your other changes here (docker-compose and README updates).

Also, thank you in particular for the README improvements; those are certainly needed (#9, #21, #23).

**Comment by theonlytruebigmac** [comment]
@cdzombak @ablyler thanks for the review, I'll check this out and make adjustments!

**Pull request closed without merging**
