### PR TITLE
add initial docker support

### PR DESCRIPTION
**Pull request by ablyler**
Documentation needs to be updated to note that a /config volume needs to be created that contains the config.json file. This is also the volume that the creds will be cached into.

### CODE REVIEW

**Comment by cdzombak** [comment]
> Documentation needs to be updated to note that a /config volume needs to be created that contains the config.json file. This is also the volume that the creds will be cached into.

@ablyler would you mind updating the README with a section on deployment with Docker, as part of this PR, when you have some time?

**Comment by ablyler** [comment]
@cdzombak done!

**Review by cdzombak — APPROVED** [review]

**Comment by cdzombak** [comment]
@ablyler thank you!

**Comment by ablyler** [comment]
@cdzombak don't forget to add the docker secrets to enable publishing of the docker image to docker hub.

**Comment by cdzombak** [comment]
@ablyler I just added them.

**Pull request merged**
